# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anti', '0002_auto_20180603_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
    ]
